name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build App
        run: yarn build

      - name: Upload Production Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Install Serve Globally
        run: yarn global add serve

      - name: Run Serve in Background
        run: nohup serve -s build -l 30000 &

      - name: Wait for Server
        run: sleep 10

      - name: Curl for React App
        run: |
          curl http://localhost:30000 | grep "React App"
