# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI-CD and Building Docker FIle

on:
  push:
    branches: [ "main","feature-docker-build-deploy" ]
  pull_request:
    branches: [ "main","feature-docker-build-deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:   #dont need it if wanted to use just one version
      matrix:    
        node-version: [18.x]   
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npm test
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/
    

  test:

    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies (serve)
        run: npm install -g serve
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Productions face testing
        run: serve -s build &
      - run: sleep 10
      - run: curl -s http://localhost:3000 | grep "React App"

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts Build Folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Build Docker IMage
        uses: docker/build-push-action@v6.18.0

    

      


    
    

    
